services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
